/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JD2DPCRTOptions.java
 *
 * Created on 02-sep-2010, 13:56:18
 */

package jdicom2dose;

/**
 *
 * @author u16066
 */
public class JD2DPCRTOptions extends javax.swing.JDialog {

    private JD2DSettings set;

    /** Creates new form JD2DPCRTOptions */
    public JD2DPCRTOptions(JD2DSettings s) {
        initComponents();
        set=s;
        this.txtNumPix.setText(String.valueOf(set.getNumPixPCRT()));
        this.chkInterp.setSelected(set.isInterpPCRTFiles());
        this.chkRename.setSelected(set.isRenamePCRTFiles());
        changeInter();
    }

    private void changeInter() {
        if (this.chkInterp.isSelected()){
            this.txtNumPix.setEnabled(true);
        }
        else {
            this.txtNumPix.setEnabled(false);
        }
        //System.getProperties().
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumPix = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chkInterp = new javax.swing.JCheckBox();
        chkRename = new javax.swing.JCheckBox();
        butAccept = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jdicom2dose.JDicom2DoseApp.class).getContext().getResourceMap(JD2DPCRTOptions.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImages(null);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Form"); // NOI18N
        setResizable(false);

        txtNumPix.setFont(resourceMap.getFont("txtNumPix.font")); // NOI18N
        txtNumPix.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumPix.setText(resourceMap.getString("txtNumPix.text")); // NOI18N
        txtNumPix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumPix.setName("txtNumPix"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jCheckBox1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        chkInterp.setFont(resourceMap.getFont("chkInterp.font")); // NOI18N
        chkInterp.setText(resourceMap.getString("chkInterp.text")); // NOI18N
        chkInterp.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        chkInterp.setBorderPaintedFlat(true);
        chkInterp.setName("chkInterp"); // NOI18N
        chkInterp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInterpActionPerformed(evt);
            }
        });

        chkRename.setFont(resourceMap.getFont("jCheckBox1.font")); // NOI18N
        chkRename.setSelected(true);
        chkRename.setText(resourceMap.getString("chkRename.text")); // NOI18N
        chkRename.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        chkRename.setBorderPaintedFlat(true);
        chkRename.setName("chkRename"); // NOI18N

        butAccept.setFont(resourceMap.getFont("butAccept.font")); // NOI18N
        butAccept.setText(resourceMap.getString("butAccept.text")); // NOI18N
        butAccept.setName("butAccept"); // NOI18N
        butAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAcceptActionPerformed(evt);
            }
        });

        butCancel.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        butCancel.setText(resourceMap.getString("butCancel.text")); // NOI18N
        butCancel.setName("butCancel"); // NOI18N
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkRename)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkInterp)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumPix, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(butAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkRename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkInterp)
                    .addComponent(txtNumPix, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription(resourceMap.getString("Form.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void chkInterpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInterpActionPerformed
        changeInter();
    }//GEN-LAST:event_chkInterpActionPerformed

    private void butAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAcceptActionPerformed
        set.setNumPixPCRT(Integer.parseInt(this.txtNumPix.getText()));
        set.setInterpPCRTFiles(this.chkInterp.isSelected());
        set.setRenamePCRTFiles(this.chkRename.isSelected());
        set.storeXML();
        this.dispose();
    }//GEN-LAST:event_butAcceptActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAccept;
    private javax.swing.JButton butCancel;
    private javax.swing.JCheckBox chkInterp;
    private javax.swing.JCheckBox chkRename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumPix;
    // End of variables declaration//GEN-END:variables

}
