/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JD2DPCRTOptions.java
 *
 * Created on 02-sep-2010, 13:56:18
 */

package jdicom2dose;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.io.File;
import java.text.DecimalFormat;

/**
 *
 * @author u16066
 */
public class JD2DGeneralConfig extends javax.swing.JDialog {

    private JD2DSettings set;
    private DecimalFormat df1Dec = new DecimalFormat("####0.0");

    /** Creates new form JD2DPCRTOptions */
    public JD2DGeneralConfig(JD2DSettings s) {
        initComponents();
        set=s;
        this.txtWorkPath.setText(set.getWorkPath());
        this.txtConfigPath.setText(set.getConfigPath());
        this.txtNumPixIntDefX.setText(String.valueOf(set.getNumPixIntDefX()));
        this.txtNumPixIntDefY.setText(String.valueOf(set.getNumPixIntDefY()));
        this.txtROI_X1.setText(df1Dec.format(set.getX1ForROI()));
        this.txtROI_X2.setText(df1Dec.format(set.getX2ForROI()));
        this.txtROI_Y1.setText(df1Dec.format(set.getY1ForROI()));
        this.txtROI_Y2.setText(df1Dec.format(set.getY2ForROI()));
        this.chkWillRenameFiles.setSelected(set.isRenameFiless());
        this.chkActivateInterpolation.setSelected(set.isInterpolateFiles());
        this.chkGenerateASCII.setSelected(set.isGenerateASCIIFile());
        this.chkGenerateTIFF.setSelected(set.isGenerateTIFFile());
        this.chkToIsocenter.setSelected(set.isTrasl2Isocenter());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWorkPath = new javax.swing.JTextField();
        lvlWorkPath = new javax.swing.JLabel();
        butAccept = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();
        butWorkPath = new javax.swing.JButton();
        lvlConfigPath = new javax.swing.JLabel();
        txtConfigPath = new javax.swing.JTextField();
        butConfigPath = new javax.swing.JButton();
        lvlInter1 = new javax.swing.JLabel();
        txtNumPixIntDefX = new javax.swing.JTextField();
        lvlInter2 = new javax.swing.JLabel();
        txtNumPixIntDefY = new javax.swing.JTextField();
        lvlInter3 = new javax.swing.JLabel();
        chkGenerateASCII = new javax.swing.JCheckBox();
        chkGenerateTIFF = new javax.swing.JCheckBox();
        chkActivateInterpolation = new javax.swing.JCheckBox();
        chkToIsocenter = new javax.swing.JCheckBox();
        chkWillRenameFiles = new javax.swing.JCheckBox();
        lvlROI = new javax.swing.JLabel();
        lvlROI1 = new javax.swing.JLabel();
        lvlROI2 = new javax.swing.JLabel();
        lvlROI3 = new javax.swing.JLabel();
        lvlROI4 = new javax.swing.JLabel();
        txtROI_X1 = new javax.swing.JTextField();
        txtROI_X2 = new javax.swing.JTextField();
        txtROI_Y1 = new javax.swing.JTextField();
        txtROI_Y2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jdicom2dose.JDicom2DoseApp.class).getContext().getResourceMap(JD2DGeneralConfig.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImages(null);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setName("Form"); // NOI18N
        setResizable(false);

        txtWorkPath.setEditable(false);
        txtWorkPath.setFont(resourceMap.getFont("txtWorkPath.font")); // NOI18N
        txtWorkPath.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtWorkPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtWorkPath.setName("txtWorkPath"); // NOI18N

        lvlWorkPath.setFont(resourceMap.getFont("butAccept.font")); // NOI18N
        lvlWorkPath.setText(resourceMap.getString("lvlWorkPath.text")); // NOI18N
        lvlWorkPath.setName("lvlWorkPath"); // NOI18N

        butAccept.setFont(resourceMap.getFont("butAccept.font")); // NOI18N
        butAccept.setText(resourceMap.getString("butAccept.text")); // NOI18N
        butAccept.setName("butAccept"); // NOI18N
        butAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAcceptActionPerformed(evt);
            }
        });

        butCancel.setFont(resourceMap.getFont("butAccept.font")); // NOI18N
        butCancel.setText(resourceMap.getString("butCancel.text")); // NOI18N
        butCancel.setName("butCancel"); // NOI18N
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butWorkPath.setFont(resourceMap.getFont("butAccept.font")); // NOI18N
        butWorkPath.setText(resourceMap.getString("butWorkPath.text")); // NOI18N
        butWorkPath.setName("butWorkPath"); // NOI18N
        butWorkPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butWorkPathActionPerformed(evt);
            }
        });

        lvlConfigPath.setFont(resourceMap.getFont("lvlConfigPath.font")); // NOI18N
        lvlConfigPath.setText(resourceMap.getString("lvlConfigPath.text")); // NOI18N
        lvlConfigPath.setName("lvlConfigPath"); // NOI18N

        txtConfigPath.setEditable(false);
        txtConfigPath.setFont(resourceMap.getFont("txtConfigPath.font")); // NOI18N
        txtConfigPath.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConfigPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtConfigPath.setName("txtConfigPath"); // NOI18N

        butConfigPath.setFont(resourceMap.getFont("butConfigPath.font")); // NOI18N
        butConfigPath.setText(resourceMap.getString("butConfigPath.text")); // NOI18N
        butConfigPath.setName("butConfigPath"); // NOI18N
        butConfigPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfigPathActionPerformed(evt);
            }
        });

        lvlInter1.setFont(resourceMap.getFont("lvlInter1.font")); // NOI18N
        lvlInter1.setText(resourceMap.getString("lvlInter1.text")); // NOI18N
        lvlInter1.setName("lvlInter1"); // NOI18N

        txtNumPixIntDefX.setFont(resourceMap.getFont("txtNumPixIntDefX.font")); // NOI18N
        txtNumPixIntDefX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumPixIntDefX.setText(resourceMap.getString("txtNumPixIntDefX.text")); // NOI18N
        txtNumPixIntDefX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumPixIntDefX.setName("txtNumPixIntDefX"); // NOI18N

        lvlInter2.setFont(resourceMap.getFont("lvlInter2.font")); // NOI18N
        lvlInter2.setText(resourceMap.getString("lvlInter2.text")); // NOI18N
        lvlInter2.setName("lvlInter2"); // NOI18N

        txtNumPixIntDefY.setFont(resourceMap.getFont("txtNumPixIntDefY.font")); // NOI18N
        txtNumPixIntDefY.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumPixIntDefY.setText(resourceMap.getString("txtNumPixIntDefY.text")); // NOI18N
        txtNumPixIntDefY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumPixIntDefY.setName("txtNumPixIntDefY"); // NOI18N

        lvlInter3.setFont(resourceMap.getFont("lvlInter3.font")); // NOI18N
        lvlInter3.setText(resourceMap.getString("lvlInter3.text")); // NOI18N
        lvlInter3.setName("lvlInter3"); // NOI18N

        chkGenerateASCII.setFont(resourceMap.getFont("chkGenerateASCII.font")); // NOI18N
        chkGenerateASCII.setSelected(true);
        chkGenerateASCII.setText(resourceMap.getString("chkGenerateASCII.text")); // NOI18N
        chkGenerateASCII.setName("chkGenerateASCII"); // NOI18N

        chkGenerateTIFF.setFont(resourceMap.getFont("chkGenerateTIFF.font")); // NOI18N
        chkGenerateTIFF.setText(resourceMap.getString("chkGenerateTIFF.text")); // NOI18N
        chkGenerateTIFF.setName("chkGenerateTIFF"); // NOI18N

        chkActivateInterpolation.setFont(resourceMap.getFont("chkActivateInterpolation.font")); // NOI18N
        chkActivateInterpolation.setText(resourceMap.getString("chkActivateInterpolation.text")); // NOI18N
        chkActivateInterpolation.setName("chkActivateInterpolation"); // NOI18N

        chkToIsocenter.setFont(resourceMap.getFont("chkToIsocenter.font")); // NOI18N
        chkToIsocenter.setSelected(true);
        chkToIsocenter.setText(resourceMap.getString("chkToIsocenter.text")); // NOI18N
        chkToIsocenter.setName("chkToIsocenter"); // NOI18N

        chkWillRenameFiles.setFont(resourceMap.getFont("chkWillRenameFiles.font")); // NOI18N
        chkWillRenameFiles.setSelected(true);
        chkWillRenameFiles.setText(resourceMap.getString("chkWillRenameFiles.text")); // NOI18N
        chkWillRenameFiles.setName("chkWillRenameFiles"); // NOI18N

        lvlROI.setFont(resourceMap.getFont("lvlROI.font")); // NOI18N
        lvlROI.setText(resourceMap.getString("lvlROI.text")); // NOI18N
        lvlROI.setName("lvlROI"); // NOI18N

        lvlROI1.setFont(resourceMap.getFont("lvlROI1.font")); // NOI18N
        lvlROI1.setText(resourceMap.getString("lvlROI1.text")); // NOI18N
        lvlROI1.setName("lvlROI1"); // NOI18N

        lvlROI2.setFont(resourceMap.getFont("lvlROI2.font")); // NOI18N
        lvlROI2.setText(resourceMap.getString("lvlROI2.text")); // NOI18N
        lvlROI2.setName("lvlROI2"); // NOI18N

        lvlROI3.setFont(resourceMap.getFont("lvlROI3.font")); // NOI18N
        lvlROI3.setText(resourceMap.getString("lvlROI3.text")); // NOI18N
        lvlROI3.setName("lvlROI3"); // NOI18N

        lvlROI4.setFont(resourceMap.getFont("lvlROI4.font")); // NOI18N
        lvlROI4.setText(resourceMap.getString("lvlROI4.text")); // NOI18N
        lvlROI4.setName("lvlROI4"); // NOI18N

        txtROI_X1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtROI_X1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtROI_X1.setName("txtROI_X1"); // NOI18N

        txtROI_X2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtROI_X2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtROI_X2.setName("txtROI_X2"); // NOI18N

        txtROI_Y1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtROI_Y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtROI_Y1.setName("txtROI_Y1"); // NOI18N

        txtROI_Y2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtROI_Y2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtROI_Y2.setName("txtROI_Y2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvlWorkPath, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lvlConfigPath, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lvlInter1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lvlROI)
                                .addGap(60, 60, 60)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtWorkPath)
                                    .addComponent(txtConfigPath, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(butWorkPath, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(butConfigPath, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(txtNumPixIntDefX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lvlInter2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lvlROI1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtROI_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lvlROI2)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(txtROI_X2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lvlROI3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtROI_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lvlROI4)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtROI_Y2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumPixIntDefY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lvlInter3)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkWillRenameFiles)
                            .addComponent(chkToIsocenter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(butAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkGenerateASCII)
                            .addComponent(chkGenerateTIFF)
                            .addComponent(chkActivateInterpolation))
                        .addContainerGap(365, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtROI_X1, txtROI_X2, txtROI_Y1, txtROI_Y2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlWorkPath)
                    .addComponent(txtWorkPath, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butWorkPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlConfigPath)
                    .addComponent(txtConfigPath, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butConfigPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumPixIntDefX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlInter2)
                    .addComponent(txtNumPixIntDefY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlInter3)
                    .addComponent(lvlInter1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlROI)
                    .addComponent(lvlROI1)
                    .addComponent(txtROI_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtROI_X2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlROI2)
                    .addComponent(lvlROI3)
                    .addComponent(txtROI_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlROI4)
                    .addComponent(txtROI_Y2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkActivateInterpolation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkGenerateTIFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkGenerateASCII)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkToIsocenter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkWillRenameFiles))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAcceptActionPerformed
        set.setWorkPath(this.txtWorkPath.getText());
        set.setConfigPath(this.txtConfigPath.getText());
        set.setNumPixIntDefX(Integer.parseInt(this.txtNumPixIntDefX.getText()));
        set.setNumPixIntDefY(Integer.parseInt(this.txtNumPixIntDefY.getText()));
        set.setX1ForROI(Double.parseDouble(this.txtROI_X1.getText().replace(",", ".")));
        set.setX2ForROI(Double.parseDouble(this.txtROI_X2.getText().replace(",", ".")));
        set.setY1ForROI(Double.parseDouble(this.txtROI_Y1.getText().replace(",", ".")));
        set.setY2ForROI(Double.parseDouble(this.txtROI_Y2.getText().replace(",", ".")));
        set.setGenerateASCIIFile(this.chkGenerateASCII.isSelected());
        set.setGenerateTIFFile(this.chkGenerateTIFF.isSelected());
        set.setInterpolateFiles(this.chkActivateInterpolation.isSelected());
        set.setTrasl2Isocenter(this.chkToIsocenter.isSelected());
        set.setRenameFiles(this.chkWillRenameFiles.isSelected());
        if (set.getX1ForROI()>=set.getX2ForROI()) {
            JOptionPane.showMessageDialog(rootPane,"Ocurrió un error: Los valores de X para el ROI no son válidos, desde debe de ser menos que a.");
            return;
        }
        if (set.getY1ForROI()>=set.getY2ForROI()) {
            JOptionPane.showMessageDialog(rootPane,"Ocurrió un error: Los valores de Y para el ROI no son válidos, desde debe de ser menos que a.");
            return;
        }
        set.storeXML();
        this.dispose();
    }//GEN-LAST:event_butAcceptActionPerformed

    private void butWorkPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butWorkPathActionPerformed
        JFileChooser cho = new JFileChooser();
        cho.setMultiSelectionEnabled(false);
        cho.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File flPath = new File(set.getWorkPath());
        if (flPath.exists()) {
            cho.setCurrentDirectory(new File(set.getWorkPath()));
        }
        JFrame mainFrame = JDicom2DoseApp.getApplication().getMainFrame();
        int iRes = cho.showOpenDialog(mainFrame);
        if (iRes == JFileChooser.APPROVE_OPTION) {
            this.txtWorkPath.setText(cho.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_butWorkPathActionPerformed

    private void butConfigPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfigPathActionPerformed
        JFileChooser cho = new JFileChooser();
        cho.setMultiSelectionEnabled(false);
        cho.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File flPath = new File(set.getConfigPath());
        if (flPath.exists()) {
            cho.setCurrentDirectory(new File(set.getConfigPath()));
        }
        JFrame mainFrame = JDicom2DoseApp.getApplication().getMainFrame();
        int iRes = cho.showOpenDialog(mainFrame);
        if (iRes == JFileChooser.APPROVE_OPTION) {
            this.txtConfigPath.setText(cho.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_butConfigPathActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAccept;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butConfigPath;
    private javax.swing.JButton butWorkPath;
    private javax.swing.JCheckBox chkActivateInterpolation;
    private javax.swing.JCheckBox chkGenerateASCII;
    private javax.swing.JCheckBox chkGenerateTIFF;
    private javax.swing.JCheckBox chkToIsocenter;
    private javax.swing.JCheckBox chkWillRenameFiles;
    private javax.swing.JLabel lvlConfigPath;
    private javax.swing.JLabel lvlInter1;
    private javax.swing.JLabel lvlInter2;
    private javax.swing.JLabel lvlInter3;
    private javax.swing.JLabel lvlROI;
    private javax.swing.JLabel lvlROI1;
    private javax.swing.JLabel lvlROI2;
    private javax.swing.JLabel lvlROI3;
    private javax.swing.JLabel lvlROI4;
    private javax.swing.JLabel lvlWorkPath;
    private javax.swing.JTextField txtConfigPath;
    private javax.swing.JTextField txtNumPixIntDefX;
    private javax.swing.JTextField txtNumPixIntDefY;
    private javax.swing.JTextField txtROI_X1;
    private javax.swing.JTextField txtROI_X2;
    private javax.swing.JTextField txtROI_Y1;
    private javax.swing.JTextField txtROI_Y2;
    private javax.swing.JTextField txtWorkPath;
    // End of variables declaration//GEN-END:variables

}
